### PR TITLE
Feature/testing

### PR DESCRIPTION
**Pull request by r-ahmed2022**
In this PR, We completed the following:-
1.  Test run of calculate and operate
2.  Use Jest snapshots to test the components.
3.  React Testing Library to simulate user interaction.

### CODE REVIEW

**Review by Whoistolu — COMMENTED** [review]
Hi Team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a pair-programming project that needs equal contributions from both partners but unfortunately, you are the only one who has contributed to this project. Kindly ensure that your partner contributes to this project as this helps strengthen your team collaboration skills.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by r-ahmed2022** [comment]
Have worked on this PR alone as my learning partner has severe electricity and internet issues in his region, beyond his control. It was severely delaying our work and the same reason for the delay in submitting our work. Therefore, I have worked alone on this PR and have communicated the same to the Microverse team.

**Comment by topeogunleye** [comment]
> Have worked on this PR alone as my learning partner has severe electricity and internet issues in his region, beyond his control. It was severely delaying our work and the same reason for the delay in submitting our work. Therefore, I have worked alone on this PR and have communicated the same to the Microverse team.

Can You please include the response from the Microverse team in your PR description?

**Review by topeogunleye — COMMENTED** [review]
Hi @r-ahmed2022, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a pair programming project with no contributions from your partner.  Kindly report any issue you had with your partner to the student's success team and they'll permit you to work solo or look for a suitable partner, then include the report from student success in your PR description.

## Invalid Code Review Request ⚠️

- You have submitted a project, that does not have running linters. Please ensure that your linters are running before you submit for review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Review by AmaduKamara — COMMENTED** [review]
# Status: Invalid Submission ❌❌❌ 

Hi @r-ahmed2022, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that is having conflicts. Kindly resolve the conflicts and then resubmit for review. 👍 
- [ ] Also, kindly include proof of confirmation or feedback given by the Microverse student success team on your case as to why it's only you who worked alone on this project 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

**Comment by r-ahmed2022** [comment]
@AmaduKamara , the coding partner had worked on this PR as seen in the tree .  Also, the conflicts are not part of this PR. It is  because of Netlify deployment error

**Comment by AmaduKamara** [comment]
Ok bro, I'll suggest you cancel the deployment. I'm not sure you're asked to deploy the app. So you can cancel the deployment so the conflict is resolved. The project will only be reviewed if there are no conflicts. Please remove the deployment or if it's a must to deploy, I'm sure you can redo it so you don't have any conflict. 👍

**Review by Ugboaja-Uchechi — COMMENTED** [review]
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the PR is closed and deleted. Kindly create a valid PR for this milestone and re-submit 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Pull request closed without merging**
